export const FREE_PRACTICE_ACTIVE = 'FREE_PRACTICE_ACTIVE';
export const FREE_PRACTICE_ACTIVE_STANDINGS = 'FREE_PRACTICE_ACTIVE_STANDINGS';
export const FREE_PRACTICE_EVENTS = 'FREE_PRACTICE_EVENTS';
export const FREE_PRACTICE_UPCOMING = 'FREE_PRACTICE_UPCOMING';
