export const EVENTS_ACTIVE = 'EVENTS_ACTIVE';
export const EVENTS_FREE_PRACTICE_1 = 'EVENTS_FREE_PRACTICE_1';
export const EVENTS_FREE_PRACTICE_2 = 'EVENTS_FREE_PRACTICE_2';
export const EVENTS_FREE_PRACTICE_3 = 'EVENTS_FREE_PRACTICE_3';
export const EVENTS_QUALIFYING = 'EVENTS_QUALIFYING';
export const EVENTS_RACE = 'EVENTS_RACE';
export const EVENTS_UPCOMING = 'EVENTS_UPCOMING';
