export const STANDINGS_FREE_PRACTICE_1 = 'STANDINGS_FREE_PRACTICE_1';
export const STANDINGS_FREE_PRACTICE_2 = 'STANDINGS_FREE_PRACTICE_2';
export const STANDINGS_FREE_PRACTICE_3 = 'STANDINGS_FREE_PRACTICE_3';
export const STANDINGS_QUALIFYING = 'STANDINGS_QUALIFYING';
export const STANDINGS_RACE = 'STANDINGS_RACE';
