export const GRAND_PRIX = 'GRAND_PRIX';
export const GRAND_PRIX_ERROR = 'GRAND_PRIX_ERROR';
export const GRAND_PRIX_LOADING = 'GRAND_PRIX_LOADING';
export const GRAND_PRIX_CIRCUIT = 'GRAND_PRIX_CIRCUIT';
export const GRAND_PRIX_ACTIVE_EVENT = 'GRAND_PRIX_ACTIVE_EVENT';
export const GRAND_PRIX_UPCOMING_EVENT = 'GRAND_PRIX_UPCOMING_EVENT';
