export default {
  'Alfa Romeo': {
    country: 'Switzerland',
    name: 'Alfa Romeo Racing Orlen',
    constructor: 'Alfa Romeo Racing - Ferrari',
    chassis: 'C41',
    powerUnit: 'Ferrari 065/6',
  },
  'Alpha Tauri': {
    country: 'Italy',
    name: 'Scuderia AlphaTauri Honda',
    constructor: 'AlphaTauri - Honda',
    chassis: 'AT02',
    powerUnit: 'Honda RA621H',
  },
  Alpine: {
    country: 'France',
    name: 'Alpine F1 Team',
    constructor: 'Alpine - Renault',
    chassis: 'A521',
    powerUnit: 'Renault E-Tech 20B',
  },
  'Aston Martin': {
    country: 'United Kingdom',
    name: 'Aston Martin Cognizant F1 Team',
    constructor: 'Aston Martin - Mercedes',
    chassis: 'AMR21',
    powerUnit: 'Mercedes-AMG F1 M12',
  },
  Ferrari: {
    country: 'Italy',
    name: 'Scuderia Ferrari Mission Winnow',
    constructor: 'Ferrari',
    chassis: 'SF21',
    powerUnit: 'Ferrari 065/6',
  },
  Haas: {
    country: 'United States',
    name: 'Uralkali Haas F1 Team',
    constructor: 'Haas - Ferrari',
    chassis: 'VF-21',
    powerUnit: 'Ferrari 065/6',
  },
  McLaren: {
    country: 'United Kingdom',
    name: 'McLaren F1 Team',
    constructor: 'McLaren - Mercedes',
    chassis: 'MCL35M',
    powerUnit: 'Mercedes-AMG F1 M12',
  },
  Mercedes: {
    country: 'Germany',
    name: 'Mercedes - AMG Petronas F1 Team',
    constructor: 'Mercedes',
    chassis: 'F1 W12',
    powerUnit: 'Mercedes-AMG F1 M12',
  },
  'Red Bull': {
    country: 'Austria',
    name: 'Red Bull Racing Honda',
    constructor: 'Red Bull Racing - Honda',
    chassis: 'RB16B',
    powerUnit: 'Honda RA621H',
  },
  Williams: {
    country: 'United Kingdom',
    name: 'Williams Racing',
    constructor: 'Williams - Mercedes',
    chassis: 'FW43B',
    powerUnit: 'Mercedes-AMG F1 M12',
  },
};
